#!/bin/bash

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:
YEAR=2018
NEVENTS=-1

while getopts "h?y:i:n:d" opt; do
    case "$opt" in
    h|\?)
        #echo "triboson-gensim -y YEAR -s SAMPLE -n NEVENTS -o OUTPUT_DIR [-d]
        #If the -d (dry run) flag is set, only the environment and the config file will be created.
        #Otherwise, the cmsRun command will be executed and the working directory cleaned up afterwards."
        exit 0
        ;;
    y)  YEAR=$OPTARG
        # e.g. 2016, 2017, 2018
        ;;
    i)  INPUT=$OPTARG
        ;;
    d)  DRY_RUN=1
        # Only setup but exit script before actually running cmsRun
        ;;
    n)  NEVENTS=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))

if [ -z "$NEVENTS" ]
then
      echo "-n NEVENTS not specified!"
      exit 1
fi

shift $((OPTIND-1))

if [ -z "$INPUT" ]
then
      echo "-i INPUT not specified!"
      exit 1
fi

case "$YEAR" in

2016)  echo "The year $YEAR is not supported!"
    exit 1
    ;;
2017)  echo "The year $YEAR is not supported!"
    exit 1
    ;;
2018)  echo "The year is $YEAR"
    CONDITIONS=102X_upgrade2018_realistic_v20 \
    CAMPAIGN=RunIIAutumn18
    ;;
*) echo "Year $YEAR is not valid, did you forget to specify it with the -y option?"
   exit 1
   ;;
esac

if [ "$DRY_RUN" ]
then
      echo "Script will be exited after config file is generated"
else
      echo "The full script will be run, including the cmsRun command and cleaning on the directory"
fi


CMSSW_VERSION=CMSSW_10_2_22

# The following part should not be manually configured

ERA=Run2_${YEAR}
NANOERA=$ERA,run2_nanoAOD_102Xv1

source /cvmfs/cms.cern.ch/cmsset_default.sh
if [ -r $CMSSW_VERSION/src ] ; then
 echo release $CMSSW_VERSION already exists
else
scram p CMSSW $CMSSW_VERSION
fi
cd $CMSSW_VERSION/src
eval `scram runtime -sh`

# Patch to have the improved weight producer for NanoAOD
git cms-merge-topic guitargeek:LHEWeightsTableProducer_10_2_22

scram b -j8
cd ../../


NTHREADS=1
PILEUP_INPUT="/store/mc/RunIISummer17PrePremix/Neutrino_E-10_gun/GEN-SIM-DIGI-RAW/PUAutumn18_102X_upgrade2018_realistic_v15-v1/00002/1C56C5CD-24BC-A841-A5D5-FD70C468F890.root"


STEP0_NAME=${INPUT}-${CAMPAIGN}wmLHEGS
STEP1_NAME=${INPUT}-${CAMPAIGN}DRPremix_step1
STEP2_NAME=${INPUT}-${CAMPAIGN}DRPremix
STEP3_NAME=${INPUT}-${CAMPAIGN}MiniAOD
STEP4_NAME=${INPUT}-${CAMPAIGN}NanoAODv7

cmsDriver.py step1 \
    --filein file:${STEP0_NAME}.root \
    --fileout file:${STEP1_NAME}.root \
    --pileup_input $PILEUP_INPUT \
    --mc \
    --eventcontent PREMIXRAW \
    --datatier GEN-SIM-RAW \
    --conditions $CONDITIONS \
    --step DIGI,DATAMIX,L1,DIGI2RAW,HLT:@relval$YEAR \
    --procModifiers premix_stage2 \
    --nThreads $NTHREADS \
    --geometry DB:Extended \
    --datamix PreMix \
    --era $ERA \
    --python_filename ${STEP1_NAME}_cfg.py \
    --no_exec \
    --customise Configuration/DataProcessing/Utils.addMonitoring \
    -n $NEVENTS

cmsDriver.py step2 \
    --filein file:${STEP1_NAME}.root \
    --fileout file:${STEP2_NAME}.root \
    --mc \
    --eventcontent AODSIM \
    --runUnscheduled \
    --datatier AODSIM \
    --conditions $CONDITIONS \
    --step RAW2DIGI,L1Reco,RECO,RECOSIM,EI \
    --procModifiers premix_stage2 \
    --nThreads $NTHREADS \
    --era $ERA \
    --python_filename ${STEP2_NAME}_cfg.py \
    --no_exec \
    --customise Configuration/DataProcessing/Utils.addMonitoring \
    -n $NEVENTS

cmsDriver.py step1 \
    --filein file:${STEP2_NAME}.root \
    --fileout file:${STEP3_NAME}.root \
    --mc \
    --eventcontent MINIAODSIM \
    --runUnscheduled \
    --datatier MINIAODSIM \
    --conditions $CONDITIONS \
    --step PAT \
    --nThreads $NTHREADS \
    --geometry DB:Extended \
    --era $ERA \
    --python_filename ${STEP3_NAME}_cfg.py \
    --no_exec \
    --customise Configuration/DataProcessing/Utils.addMonitoring \
    -n $NEVENTS

cmsDriver.py step1 \
    --filein file:${STEP3_NAME}.root \
    --fileout file:${STEP4_NAME}.root \
    --mc \
    --eventcontent NANOAODSIM \
    --datatier NANOAODSIM \
    --conditions $CONDITIONS \
    --step NANO \
    --nThreads $NTHREADS \
    --era $NANOERA \
    --python_filename ${STEP4_NAME}_cfg.py \
    --no_exec \
    --customise Configuration/DataProcessing/Utils.addMonitoring \
    -n $NEVENTS

# Validate the config files
python2 ${STEP1_NAME}_cfg.py
python2 ${STEP2_NAME}_cfg.py
python2 ${STEP3_NAME}_cfg.py
python2 ${STEP4_NAME}_cfg.py

if [ "$DRY_RUN" ]
then
      exit 1
fi

cmsRun ${STEP1_NAME}_cfg.py
cmsRun ${STEP2_NAME}_cfg.py
cmsRun ${STEP3_NAME}_cfg.py
cmsRun ${STEP4_NAME}_cfg.py

# cleanup
rm -rf $CMSSW_VERSION
#rm *_cfg.py
